language: ruby
rvm:
  - 2.5.1

addons:
  ssh_known_hosts: build.archlinuxcn.org

services:
    - postgresql

before_script:
  - psql -c 'create database kiss2u_test;' -U postgres

before_deploy:
  - openssl aes-256-cbc -K $encrypted_1adf1ad1cb9b_key -iv $encrypted_1adf1ad1cb9b_iv -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script: cat .deploylist | xargs tar -cJf - | ssh a-wing@build.archlinuxcn.org 'mkdir -p .srv/KISS2U && cd .srv/KISS2U && tar -xJf - '
    on:
      branch: master

